"""
Django settings for tp project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0z%=-!yu73z7)6l+2r!_05h*(zw0np-r&!pbhn3hbgj_%lx3a!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "app"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Directories where Django will look for static files (in addition to each app’s `static/` folder)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # Títulos
    "site_title": "Gestión de Turnos Médicos",
    "site_header": "Sistema Clínico",
    "site_brand": "Turnos Médicos DAO",

    # Sidebar / Navegación
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Menú Principal Personalizado
    # Esto reemplaza el menú automático por una estructura definida.
    "usermenu_links": [
        {"name": "Soporte", "url": "https://tu-url-de-soporte.com", "new_window": True},
        {"model": "auth.user"},
    ],

    "custom_links": {
        "app": [{  # Reemplaza 'app' con el nombre de tu aplicación Django
            "name": "Reporte de Asistencia",
            "url": "admin:reporte-asistencia", # Esto asume que tienes una vista admin registrada
            "icon": "fas fa-chart-bar",
            "permissions": ["auth.view_user"]
        }]
    },

    "order_with_respect_to": [
        # 1. Módulos Esenciales y Transacción Principal
        "app.Turno",
        "app.Paciente",
        "app.Medico",
        
        # 2. Módulos Clínicos
        "app.HistorialClinico", 
        "app.Receta",
        
        # 3. Módulos de Configuración y Reportes Avanzados
        "app.Especialidad",
        "app.Recordatorio",
        "auth.Group", # Mantenemos los grupos y usuarios al final
        "auth.User",
    ],

    # Iconos (usando FontAwesome, se aplican automáticamente por defecto, pero puedes sobreescribir)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "app.Turno": "fas fa-calendar-check",
        "app.Paciente": "fas fa-hospital-user",
        "app.Medico": "fas fa-user-md",
        "app.Especialidad": "fas fa-tag",
        "app.HistorialClinico": "fas fa-file-medical",
        "app.Receta": "fas fa-prescription-bottle-alt",
        "app.Recordatorio": "fas fa-bell",
    }
}

