# Generated by Django 5.2.7 on 2025-10-15 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Especialidad')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Atención')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, null=True, verbose_name='Tratamiento / Indicaciones')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-fecha_atencion'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula Profesional')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidades', models.ManyToManyField(related_name='medicos', to='app.especialidad')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('medicamentos', models.TextField(verbose_name='Detalle de Medicamentos')),
                ('indicaciones', models.TextField(blank=True, null=True, verbose_name='Instrucciones Adicionales')),
                ('historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='app.historialclinico', verbose_name='Atención del Historial')),
            ],
            options={
                'verbose_name': 'Receta Electrónica',
                'verbose_name_plural': 'Recetas Electrónicas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora del Turno')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ATENDIDO', 'Atendido (Asistencia)'), ('CANCELADO', 'Cancelado'), ('AUSENTE', 'Ausente (Inasistencia)')], default='PENDIENTE', max_length=10)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='app.paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_hora'],
                'unique_together': {('medico', 'fecha_hora')},
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MAIL', 'Correo Electrónico'), ('SMS', 'Mensaje de Texto (SMS)'), ('NOTIF', 'Notificación en App')], default='MAIL', max_length=10)),
                ('fecha_hora_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Envío')),
                ('enviado', models.BooleanField(default=False)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='app.turno')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['fecha_hora_envio'],
            },
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.turno', verbose_name='Turno/Atención Asociada'),
        ),
    ]
