# Generated by Django 5.2.7 on 2025-10-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
